apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: grotto_monitor
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
